from urllib.error import HTTPError

from scrape_crime import scrape

JUNE_URLS = ['https://www.hupd.harvard.edu/files/hupd/files/060119.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060219.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060319.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060419.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060519.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060619.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060719.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060819.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/060919.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061019.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061119.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061219.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061319.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061419.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061519.pdf',
             'https://www.hupd.harvard.edu/files/hupd/files/061619.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061719.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061819.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/061919.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062019.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062119.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062219.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062319.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062419.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062519.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062619.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062719.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062819.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/062919.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/063019.pdf']

JULY_URLS = ['https://www.hupd.harvard.edu/files/hupd/files/070019.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070119.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070219.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070319.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070419.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070519.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070619.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070719.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070819.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/070919.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071019.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071119.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071219.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071319.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071419.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071519.pdf',
             'https://www.hupd.harvard.edu/files/hupd/files/071619.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071719.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071819.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/071919.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072019.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072119.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072219.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072319.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072419.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072519.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072619.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072719.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072819.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/072919.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/073019.pdf', 'https://www.hupd.harvard.edu/files/hupd/files/073119.pdf']

if __name__ == "__main__":
    for url in JUNE_URLS:
        try:
            scrape(url)
        except HTTPError:
            print("Skipping")
